### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by Kaos1337** [mfreiholz/ts3video-public#16]
I suggest to add a log file where collect all join and leave from the conferences rooms of any user.
This because I'm interested to understand how frequently it is used.

**Comment by mfreiholz** [comment]
Hi Kaos1337,

there already is a log file with exactly this information.
You can find it here %TEMP%/ts3video-server.log

In a future release i will include the latest logs in the web-interface.

Manuel

**Comment by Kaos1337** [comment]
I was looking for it in /var/log and the installation folder (/opt/ts3video), I wasn't thinking about the temporary folder that can be regularly cleaned in windows or completely emptied at reboot in linux.
Another suggestion: add this info in the documentation xD

**Comment by mfreiholz** [comment]
You're right, i will add this information.
