### ISSUE TITLE
Installation server issue 32/64 bits

### ISSUE THREAD

**Issue by Gadjhe** [mfreiholz/ts3video-public#6]
Dude you should check your uploaded server files, i think by mistake you uploaded both with the same version, i tried installing both 32 and 64 bit server files and none of them work i keep getting the same error plus i found out they both have the same size and date thats why i thought it could be that both are the same. Anyways gladly if u could help me out thanks.

**Comment by Gadjhe** [comment]
<a href="http://imgur.com/WObTbPE"><img src="http://i.imgur.com/WObTbPE.jpg" title="source: imgur.com" /></a>

**Comment by mfreiholz** [comment]
Oh damn you are right.
I removed the download and will upload the correct version tonight.

Thanks a lot.

**Comment by mfreiholz** [comment]
I just updated the package. You can download the correct 32-bit ZIP archive now.

Thanks for you help.

**Comment by Gadjhe** [comment]
Thanks a lot man! i thought id might be wrong so i decided to let u know, you are welcome im going to try this dude thanks again, one more thing just curiosity does "Freiholz" stands for "Frijoles" or is that a last name? "Frijoles" means "beans" in spanish since your name is Manuel thought u were messing around with the last name lol

**Comment by mfreiholz** [comment]
*loool*
Nope that is actually my real last name. :+1: 
Translated to english it would mean ~"free wood" ;-)
